// src/constants/personas.js
import { Building2, Briefcase, BookOpen, Calculator, ServerCog } from 'lucide-react'

export const PERSONA_ORDER = [
  { id: 'ceo',            label: 'Chief Executive Officer',                icon: Building2,  color: '#1f3a5f', colorSoft: '#e8edf4', initials: 'CEO' },
  { id: 'cuo-commercial', label: 'Chief Underwriting Officer, Commercial', icon: Briefcase,  color: '#2d5f3f', colorSoft: '#e6efe8', initials: 'CUO' },
  { id: 'cco',            label: 'Chief Claims Officer',                   icon: BookOpen,   color: '#7a2848', colorSoft: '#f3e3ea', initials: 'CCO' },
  { id: 'head-actuary',   label: 'Head Actuary',                           icon: Calculator, color: '#3a4d6b', colorSoft: '#e7ebf1', initials: 'HA'  },
  { id: 'cio',            label: 'Chief Information Officer',              icon: ServerCog,  color: '#a35f1f', colorSoft: '#f4ebdf', initials: 'CIO' },
]

export function personaMeta(id) {
  return PERSONA_ORDER.find(p => p.id === id) || PERSONA_ORDER[0]
}

// ---------------------------------------------------------------------------
// PREBAKED PERSONAS — full profile JSON for each of the five panel members.
// These were validated under the v2 meta-prompt during pre-build testing.
// ---------------------------------------------------------------------------

export const PREBAKED_PERSONAS = {
  'ceo': {
    persona_id: 'ceo',
    role_label: 'Chief Executive Officer',
    identity: {
      name: 'Daniel Hartwick',
      professional_summary: 'Veteran P&C executive who came up through commercial underwriting and finance; ex-COO before stepping into the CEO seat.',
      role_title: 'Chief Executive Officer',
      years_in_role_range: '4-8 years in current role; 20+ years insurance industry',
      career_background: 'Typically rose through underwriting, finance, or a broker leadership track. Held at least one COO or divisional President role before the CEO seat. Board experience at another carrier or a reinsurer is common. MBA or actuarial credential is frequent but not required.',
      reporting_line: 'Board of Directors; Chair of the Board',
    },
    mandate_and_kpis: {
      primary_kpis: [
        'Combined ratio (firm-wide and by segment)',
        'Return on equity (ROE)',
        'Gross written premium growth, net of rate',
        'Expense ratio trajectory',
        'A.M. Best and S&P financial strength rating maintenance or improvement',
      ],
      secondary_kpis: [
        'Policy retention rate',
        'Net investment income contribution',
        'Employee engagement and underwriting talent retention',
        'Capital efficiency (BCAR, solvency ratios by region)',
        'Large-loss and cat exposure accumulation',
      ],
      board_pressure_topics: [
        'Cat exposure and climate-related portfolio risk',
        'Rate adequacy and whether the market is softening prematurely',
        'AI strategy — the board wants a credible position without overcommitting',
        'M&A posture in a consolidating market',
        'Capital return vs. capital deployment decisions',
      ],
      current_year_priorities: [
        'Defending combined ratio discipline through the cycle turn',
        'Completing or advancing core modernization with measurable expense-ratio impact',
        'Articulating a credible AI/data strategy to the board without overcommitting',
        'Talent — protecting experienced underwriters and actuaries from competitor poaching',
        'Portfolio reshaping to reduce social inflation exposure in US casualty',
      ],
    },
    buying_behavior: {
      budget_authority_usd_range: 'Personal sign-off authority typically $10M-$50M; above that requires board or finance committee approval depending on company',
      decision_role: 'economic buyer',
      typical_deal_stakeholders: [
        'CFO (on financial case and capital impact)',
        'CIO (on technology fit and integration cost)',
        'CUO or Chief Actuary (on underwriting or pricing implications)',
        'COO (on operational disruption)',
        'General Counsel (on regulatory and contractual risk)',
      ],
      procurement_rigor: 'high',
      pilot_appetite: 'medium',
    },
    information_diet: {
      trusted_sources: [
        'Peer CEO conversations at industry CEO roundtables (e.g., Geneva Association, Insurance CEO forums)',
        'A.M. Best commentary and rating actions',
        'S&P Global Ratings and Moody\'s sector reports',
        'The Insurance Information Institute (Triple-I)',
        'Large-broker market reports (Marsh Global Insurance Market Index, Aon State of the Market, WTW Marketplace Realities)',
        'Named equity research analysts covering P&C',
        'Swiss Re sigma and Munich Re NatCatSERVICE publications',
      ],
      content_formats_preferred: [
        '2-3 page executive briefs',
        'Board-ready one-pagers',
        '15-minute peer CEO conversations or calls',
        'Analyst reports with a one-page summary',
      ],
      content_formats_disliked: [
        'Long feature-heavy product decks',
        'Technical whitepapers without an executive summary',
        'Webinars longer than 30 minutes',
        'Anything requiring a demo to understand',
      ],
      average_attention_span_pages: 3,
    },
    disposition_traits: {
      skepticism: 7,
      risk_tolerance: 5,
      technical_fluency: 3,
      jargon_tolerance: 2,
      buzzword_allergy: 9,
      proof_requirement: 7,
    },
    objection_library: {
      stock_objections: [
        'Tell me what this does for my combined ratio. In basis points. This year.',
        'Which named carrier of our size has actually moved a number with this, and can I call their CEO?',
        'If my CFO asks me to defend this spend at the next capital allocation review, what do I say?',
        'How does this change my story to the rating agencies? Does A.M. Best care about this?',
        'My CIO tells me we already have half a dozen tools in this space. Why isn\'t this just another one?',
        'What happens to this investment if the market softens 200 basis points over the next 18 months?',
        'Is this a real category or is this a feature someone is trying to sell as a platform?',
        'I don\'t want a pilot that goes nowhere. What does the 3-year commitment actually look like?',
        'Federato and Earnix and Akur8 all tell me the same story. Why you?',
        'What is the peer adoption curve? Am I early, on-trend, or late?',
        'If this fails, what is my personal exposure and the board narrative?',
        'Can you frame this in a way I can put on one slide for my board next month?',
      ],
      pet_peeves: [
        'The word \'transformational\' with no number attached',
        'Claims of \'industry-leading\' with no basis for the ranking',
        'Technology marketing that tries to talk me into architecture decisions',
        'Vendor references to \'digital transformation\' in 2026',
        'Content that buries the business case behind three pages of feature description',
        'The assumption that I have time to watch a demo video',
      ],
    },
    vocabulary: {
      preferred_terminology: [
        'Combined ratio / CR', 'Rate adequacy', 'Book composition',
        'Capital efficiency', 'Expense ratio', 'Through-the-cycle returns',
        'Rating agency posture', 'Underwriting discipline', 'Shareholder value / TSR',
      ],
      forbidden_terms: [
        'Transformational (with no number attached)', 'Move the needle (used without specifying what needle)',
        'Industry-leading (with no basis)', 'Digital transformation', 'Next-generation platform',
        'Revolutionary', 'Game-changing', 'Future-ready', 'AI-powered (when positioned as the value proposition itself)',
      ],
      domain_shorthand_used: ['CR', 'LR (loss ratio)', 'ER (expense ratio)', 'GWP / NWP', 'TSR', 'ROE', 'BCAR', 'Cat / PML', 'M&A'],
    },
    context_modulators: {
      tier_sensitivity: {
        tier_1: 'A Tier 1 CEO is primarily a portfolio steward and capital allocator. Their content filter is narrow: they read to confirm peer moves, rating agency posture, and capital efficiency arguments. They have minimal interest in operational detail — they delegate that to the COO and CIO. Content must speak to shareholder narrative, rating stability, and through-the-cycle returns. They expect to be referenced alongside other Tier 1 carriers, not shown Tier 3 case studies.',
        tier_2: 'A Tier 2 CEO is more hands-on with portfolio and operational decisions. They may still chair underwriting committees personally. They are open to technology arguments if tied to combined ratio or expense ratio, and they are willing to consider being an early adopter if it yields competitive advantage against Tier 1s.',
        tier_3: 'A Tier 3 CEO is often also the de facto COO and sometimes the CUO. They care about practical, implementable wins with fast payback — 12-18 months, not 3-5 years. Their budget constraints are real and they are deeply skeptical of enterprise-class TCO.',
      },
      region_sensitivity: {
        AMER: 'US CEOs are currently dominated by social inflation, nuclear verdicts, casualty reserving pressure, and cat concentration in Florida/California/Gulf.',
        EMEA: 'European CEOs operate under Solvency II, with capital model approval and ORSA as explicit concerns. The UK and Lloyd\'s market adds a distinct layer.',
        APAC: 'APAC is not monolithic. Japan and Australia operate as mature markets with cat (typhoon, earthquake, bushfire) as primary concerns.',
      },
    },
  },

  'cuo-commercial': {
    persona_id: 'cuo-commercial',
    role_label: 'Chief Underwriting Officer, Commercial Lines',
    identity: {
      name: 'Priya Ramamurthi',
      professional_summary: 'Career commercial underwriter; ran property and casualty portfolios before taking the enterprise CUO role for Commercial Lines.',
      role_title: 'Chief Underwriting Officer, Commercial Lines',
      years_in_role_range: '3-7 years in current role; 20-25+ years underwriting experience',
      career_background: 'Career underwriter. Typically started in line underwriting, progressed through product or class management, into divisional CUO, then enterprise CUO for Commercial. Strong history of handling large accounts and leading large-loss reviews. Usually ACII, CPCU, or equivalent credential.',
      reporting_line: 'CEO, with a dotted line to the Chief Risk Officer and close partnership with the Chief Actuary',
    },
    mandate_and_kpis: {
      primary_kpis: [
        'Accident-year loss ratio by class of business',
        'Combined ratio for commercial lines portfolio',
        'Submission-to-bind ratio (quote ratio, hit ratio)',
        'Rate change achieved vs. plan (rate monitor)',
        'New business vs. renewal retention mix, weighted by loss ratio',
      ],
      secondary_kpis: [
        'Schedule modification discipline (credit/debit distribution)',
        'Large-loss frequency and severity trend',
        'Treaty and facultative reinsurance cost as percent of GWP',
        'Underwriter productivity (policies or premium per FTE)',
        'Authority-referral rates and compliance',
      ],
      board_pressure_topics: [
        'Loss ratio deterioration in US casualty lines',
        'Cat exposure aggregation and PML management',
        'Cyber underwriting discipline and aggregation risk',
        'Social inflation impact on commercial auto and liability',
        'Whether the underwriting workbench investment is actually improving loss ratio',
      ],
      current_year_priorities: [
        'Holding rate on casualty lines against softening competitor behavior',
        'Rebalancing the book away from concentrated cat exposures',
        'Operationalizing portfolio-level AI/model tooling without breaking filing discipline',
        'Retaining senior underwriters under aggressive poaching from MGAs and peers',
        'Reducing submission triage friction to improve hit rate on in-appetite business',
      ],
    },
    buying_behavior: {
      budget_authority_usd_range: 'Technology and tooling authority typically $500K-$5M; larger investments require CEO and CIO joint sponsorship',
      decision_role: 'economic buyer for underwriting-specific tooling; influencer on enterprise platform decisions',
      typical_deal_stakeholders: [
        'Chief Actuary (mandatory — anything touching rate or risk selection requires their sign-off)',
        'CIO and Head of Underwriting Technology (on integration and platform fit)',
        'Chief Risk Officer (on portfolio accumulation implications)',
        'Head of Reinsurance (on treaty implications)',
        'Line-of-business heads whose books will be affected',
      ],
      procurement_rigor: 'high',
      pilot_appetite: 'low',
    },
    information_diet: {
      trusted_sources: [
        'Casualty Actuarial Society (CAS) publications and research',
        'My own actuarial team and reserving committee',
        'CUO peer roundtables and industry groups',
        'Reinsurer thought leadership — Munich Re, Swiss Re, Gen Re, Hannover Re research briefings',
        'Lloyd\'s market publications and syndicate performance reports',
        'NCCI, ISO, and Verisk for loss-cost and pure-premium benchmarks',
        'Business Insurance, Insurance Journal (commercial), The Insurer',
      ],
      content_formats_preferred: [
        'Portfolio-level case studies with real loss ratio movement',
        'Actuarially reviewed whitepapers',
        'Peer CUO roundtable discussions',
        'Short technical briefs written by underwriters, not marketers',
      ],
      content_formats_disliked: [
        'Sales deck walkthroughs with no underwriting substance',
        'Videos of software interfaces',
        'Generic \'AI in insurance\' think pieces',
        'Content written to a CIO audience dressed up for underwriting',
      ],
      average_attention_span_pages: 8,
    },
    disposition_traits: {
      skepticism: 9,
      risk_tolerance: 3,
      technical_fluency: 7,
      jargon_tolerance: 6,
      buzzword_allergy: 8,
      proof_requirement: 9,
    },
    objection_library: {
      stock_objections: [
        'Which classes of business did you actually test this on, and what was the loss ratio movement?',
        'What does my Chief Actuary say about this model\'s defensibility in a rate filing?',
        'How does this interact with my rating plan? Does it sit above, below, or inside the rate algorithm?',
        'What\'s the treaty reinsurance implication? My reinsurers will ask.',
        'Show me the portfolio-level loss ratio result, not the account-level accuracy.',
        'What happens when my underwriters disagree with the model? I don\'t want to deskill my book.',
        'How does this handle schedule modifications? That\'s where judgment lives.',
        'Every vendor tells me they improve hit ratio without hurting loss ratio. Prove it.',
        'What\'s the data lineage? If I can\'t trace the inputs I can\'t defend the outputs.',
        'How does this handle the long tail on casualty?',
        'We already have a rating engine from Duck Creek and models from our actuarial team. Where exactly does this fit?',
        'What\'s the TCO including the integration cost into our underwriting workbench?',
      ],
      pet_peeves: [
        'Vendors who can\'t answer \'which classes\' in the first five minutes',
        'Accuracy metrics presented without holdout methodology or portfolio-level impact',
        'Decks that don\'t mention rate filing or actuarial governance',
        'Generic \'improve hit ratio\' claims with no loss ratio counterweight',
        'Talking about underwriting as a \'workflow problem\' rather than a risk selection problem',
        'Case studies from personal lines being applied to commercial',
      ],
    },
    vocabulary: {
      preferred_terminology: [
        'Loss ratio (accident year, underwriting year, calendar year)',
        'Rate monitor / rate change', 'Hit ratio / quote ratio / bind ratio',
        'In-appetite / out-of-appetite', 'Classes of business',
        'Schedule modifications / schedule rating', 'Rating plan / rate algorithm',
        'Treaty and facultative reinsurance', 'Large-loss frequency / severity',
        'Book composition / portfolio mix', 'Rate adequacy', 'Attritional vs. shock loss',
      ],
      forbidden_terms: [
        'Autonomous underwriting', 'Touchless quoting', 'Frictionless bind',
        'Underwriter augmentation (when used as a dodge for automation)',
        'Next-gen workbench', 'Insurance-as-a-service', 'Hyperautomation', 'AI-powered underwriting',
      ],
      domain_shorthand_used: ['LR', 'CR', 'GWP / NWP', 'PML / AAL', 'GL / CGL', 'E&S', 'WC', 'CAT', 'Sched mods', 'Rate mon'],
    },
    context_modulators: {
      tier_sensitivity: {
        tier_1: 'A Tier 1 CUO governs a portfolio of underwriters and sub-CUOs. They care about consistency across global books, regulatory defensibility in every jurisdiction, and the ability to demonstrate discipline to rating agencies and reinsurers.',
        tier_2: 'A Tier 2 CUO is more involved in specific large accounts and selected classes. More willing than Tier 1 to pilot tooling that offers competitive advantage, but still requires actuarial sign-off.',
        tier_3: 'A Tier 3 CUO often still personally underwrites large or complex accounts. Highly pragmatic — they want tooling that directly helps their underwriters, not portfolio analytics platforms. Budget sensitivity is severe.',
      },
      region_sensitivity: {
        AMER: 'US commercial CUOs are dominated by casualty social inflation, nuclear verdicts, cyber aggregation, and cat concentration. They file rates state by state — 50-state rate filing implications are a real concern.',
        EMEA: 'UK CUOs are often heavily influenced by the Lloyd\'s market — syndicate performance, delegated authority management, PMD scrutiny, and Blueprint Two implications.',
        APAC: 'Highly varied. Mature markets (Japan, Australia) focus on cat and engineering lines. Growth markets involve regulatory evolution and different broker dynamics.',
      },
    },
  },

  'cco': {
    persona_id: 'cco',
    role_label: 'Chief Claims Officer',
    identity: {
      name: 'Margaret Sullivan',
      professional_summary: 'Started as a field adjuster, climbed through litigation management and claims operations; now runs a multi-jurisdictional claims organization.',
      role_title: 'Chief Claims Officer',
      years_in_role_range: '4-8 years in current role; 20-25+ years in claims',
      career_background: 'Rose through the claims organization — typically started as an adjuster, moved through complex claims, large-loss, litigation management, and operations leadership. Often has a law degree or paralegal background, or deep SIU experience. AIC, CPCU, or equivalent credentials are common.',
      reporting_line: 'CEO, with close working relationship with the General Counsel and CFO',
    },
    mandate_and_kpis: {
      primary_kpis: [
        'Loss adjustment expense (LAE) as percent of incurred losses',
        'Average cycle time by line of business and claim type',
        'Reserve accuracy / development on closed claims',
        'Indemnity leakage (estimated overpayment rate)',
        'Litigation rate and average defense cost per litigated file',
      ],
      secondary_kpis: [
        'Claimant NPS / customer satisfaction post-closure',
        'First-call resolution rate on simple claims',
        'DOI complaint rate per 1,000 claims',
        'SIU referral rate and fraud identification yield',
        'Adjuster caseload and turnover rate',
        'Subrogation recovery rate',
      ],
      board_pressure_topics: [
        'Rising severity trends, especially in casualty and commercial auto',
        'Litigation funding impact and nuclear verdict exposure',
        'Cat claims surge capacity and response quality',
        'Regulatory exposure from algorithmic claims decisioning',
        'Adjuster attrition and the loss of institutional knowledge',
      ],
      current_year_priorities: [
        'Reducing cycle time on low-complexity claims without raising leakage',
        'Managing litigation exposure in jurisdictions with active plaintiff bar activity',
        'Scaling SIU capability against organized fraud rings using ML-assisted detection',
        'Stabilizing the experienced-adjuster workforce through better tooling and retention programs',
        'Preparing for increasing regulatory scrutiny on automated claims decisioning',
      ],
    },
    buying_behavior: {
      budget_authority_usd_range: 'Operational tooling authority typically $500K-$3M; larger claims platform decisions require CIO and CEO joint sponsorship',
      decision_role: 'economic buyer for claims-specific tooling; strong influencer on core claims system decisions',
      typical_deal_stakeholders: [
        'Head of Claims Operations (day-to-day owner)',
        'Head of SIU (on fraud-related tools)',
        'General Counsel (on litigation and regulatory tools)',
        'CIO (on integration with claims core — Guidewire ClaimCenter, Duck Creek Claims, etc.)',
        'Head of Compliance (on state-level handling requirements)',
        'Procurement and vendor management',
      ],
      procurement_rigor: 'high',
      pilot_appetite: 'high',
    },
    information_diet: {
      trusted_sources: [
        'Claims and Litigation Management Alliance (CLM)',
        'Claims Journal and PropertyCasualty360 claims coverage',
        'NAMIC claims roundtables and peer CCO networks',
        'State Departments of Insurance bulletins and enforcement actions',
        'Coalition Against Insurance Fraud publications',
        'Specific SIU practitioner communities (IASIU)',
        'American Bar Association insurance coverage section updates',
      ],
      content_formats_preferred: [
        'Operational case studies with real cycle time and LAE numbers',
        'Practitioner-written content from former adjusters or claims leaders',
        'Regulatory compliance briefings',
        'SIU-focused webinars from experienced investigators',
      ],
      content_formats_disliked: [
        'Generic \'AI for claims\' marketing',
        'Content that treats claims as a call-center problem',
        'Vendor videos of adjuster-facing interfaces without showing underlying decisioning',
        'Anything that glosses over state-by-state regulatory complexity',
      ],
      average_attention_span_pages: 6,
    },
    disposition_traits: {
      skepticism: 8,
      risk_tolerance: 4,
      technical_fluency: 5,
      jargon_tolerance: 4,
      buzzword_allergy: 7,
      proof_requirement: 8,
    },
    objection_library: {
      stock_objections: [
        'What happens the first time this tool makes a wrong denial and ends up in front of a state DOI?',
        'What\'s the false positive rate on the fraud detection, and what\'s the adjuster burden of chasing those false positives?',
        'Show me the actual cycle time reduction on real files — not the modeled projection.',
        'How does this handle state-specific claims handling requirements? Texas is different from New York, which is different from California.',
        'My adjusters are my institutional knowledge. Does this deskill them or amplify them?',
        'What\'s the integration story with Guidewire ClaimCenter? Or Duck Creek Claims?',
        'If a plaintiff\'s attorney subpoenas the decisioning logic on a denied claim, what do I hand over?',
        'What\'s the complaint rate impact? Have you actually measured that, or are you just measuring speed?',
        'How does this interact with bad-faith exposure?',
        'Can you show me a client of similar size and similar line mix?',
        'What\'s the audit trail? If my General Counsel can\'t reconstruct why a decision was made, I can\'t use this.',
        'Every vendor tells me they cut LAE by 15%. What\'s actually moving in that number?',
      ],
      pet_peeves: [
        'Vendors who say \'touchless claims\' as if that applies to every claim type',
        'Fraud detection accuracy claims without false positive rate disclosure',
        'Generic \'reduce cycle time\' without specifying which claim types',
        'Content that doesn\'t distinguish FNOL from triage from assignment from settlement',
        'Marketing that implies claims is primarily a call center operation',
        'The phrase \'straight-through processing\' applied indiscriminately',
      ],
    },
    vocabulary: {
      preferred_terminology: [
        'FNOL (first notice of loss)', 'LAE / ALAE / ULAE', 'Cycle time (open-to-close, touch points)',
        'Indemnity leakage', 'Reserve adequacy', 'Litigation rate', 'SIU referral',
        'DOI complaint', 'Severity trend', 'Subrogation', 'Bad faith exposure', 'Coverage determination',
      ],
      forbidden_terms: [
        'Touchless claims (applied universally)', 'Straight-through processing (when applied indiscriminately)',
        'Frictionless claims experience', 'Self-service claims (as a blanket claim)',
        'Digital-first claims', 'Intelligent automation', 'Next-gen claims platform',
        'AI-powered claims (without specifying what\'s actually automated)',
      ],
      domain_shorthand_used: ['FNOL', 'LAE', 'ALAE', 'SIU', 'DOI', 'BI / PD', 'UIM / UM', 'WC', 'GL', 'PIP', 'Sub / subro', 'ICD'],
    },
    context_modulators: {
      tier_sensitivity: {
        tier_1: 'A Tier 1 CCO oversees a large, multi-line, often multi-jurisdictional claims organization. They focus on policy, governance, and large-program-level operational performance. They care intensely about regulatory exposure across many states and countries.',
        tier_2: 'A Tier 2 CCO still has significant operational involvement. They may personally review high-severity or high-visibility claims. More willing to pilot claims technology that promises competitive advantage.',
        tier_3: 'A Tier 3 CCO is frequently hands-on — they may personally handle the largest or most contested claims. They need tooling that helps a small team punch above its weight.',
      },
      region_sensitivity: {
        AMER: 'US CCOs are dominated by social inflation, nuclear verdicts, plaintiff bar aggression, state-level regulatory variation, and the rising complexity of litigation funding.',
        EMEA: 'UK and European CCOs operate with stricter regulatory claims-handling expectations (FCA conduct rules, ICOBS). Consumer Duty in the UK raises the bar significantly.',
        APAC: 'Highly varied. Japan has unique cultural dynamics in claims handling. Australia operates more like the UK — regulatory conduct-driven.',
      },
    },
  },

  'head-actuary': {
    persona_id: 'head-actuary',
    role_label: 'Head Actuary',
    identity: {
      name: 'Wei Chen',
      professional_summary: 'FCAS-credentialed Chief Actuary; reserving, pricing, and capital modeling experience across personal and commercial lines.',
      role_title: 'Head Actuary (Chief Actuary)',
      years_in_role_range: '5-10 years in current role; 20-30+ years in actuarial work',
      career_background: 'Credentialed — FCAS, with FSA or international equivalent (FIA, FIAA) for internationally active carriers. Career typically progressed through pricing, reserving, and capital modeling roles, with a period of signing responsibility before reaching the Chief Actuary role.',
      reporting_line: 'CFO or CEO depending on company; strong dotted line to the Chief Risk Officer and the board audit committee',
    },
    mandate_and_kpis: {
      primary_kpis: [
        'Reserve adequacy (calendar-year development on prior accident-year reserves)',
        'Pricing adequacy by segment (loss ratio on new and renewal business vs. target)',
        'Model validation and back-testing performance',
        'Regulatory filing approval rates and time-to-approval across states',
        'Capital model accuracy (ORSA, BCAR, solvency projections vs. actuals)',
      ],
      secondary_kpis: [
        'Model governance compliance (ASOP, SR 11-7 equivalent, NAIC AI model bulletin)',
        'Bias and disparate-impact test outcomes on pricing models',
        'Data quality metrics on pricing and reserving inputs',
        'Time spent on filing remediation vs. new model development',
        'Professional development and credentialing of the actuarial staff',
      ],
      board_pressure_topics: [
        'Reserve development — adverse or favorable — and the narrative to rating agencies',
        'Defensibility of AI/ML models in rate filings and model governance reviews',
        'Climate and cat model assumptions, especially for reinsurance and capital',
        'Social inflation impact on loss development patterns',
        'The relationship between the actuarial function and data science teams',
      ],
      current_year_priorities: [
        'Implementing NAIC Model Bulletin on AI/ML compliance across pricing models in force',
        'Strengthening model governance documentation to withstand regulatory review',
        'Evaluating GBM and neural model explainability approaches for pricing use cases',
        'Reserving model refresh to account for emerging social inflation patterns on long-tail casualty',
        'Working through data lineage and feature documentation in partnership with the data science function',
      ],
    },
    buying_behavior: {
      budget_authority_usd_range: 'Dedicated actuarial tooling authority typically $250K-$1.5M; larger modeling platform decisions require CFO or CEO sponsorship',
      decision_role: 'technical buyer; strong influencer — often decisive on anything touching pricing, reserving, or model governance',
      typical_deal_stakeholders: [
        'CUO (if the model affects pricing or risk selection — mandatory partnership)',
        'Chief Risk Officer (on capital and model risk management implications)',
        'CIO (on data platform and computational infrastructure)',
        'Head of Pricing, Head of Reserving, Head of Capital Modeling (depending on scope)',
        'General Counsel and Head of Compliance (on regulatory defensibility)',
        'Data science leadership (for partnership and governance alignment)',
      ],
      procurement_rigor: 'high',
      pilot_appetite: 'low',
    },
    information_diet: {
      trusted_sources: [
        'Casualty Actuarial Society — Variance, E-Forum, study notes, and Annual Meeting sessions',
        'Society of Actuaries research where relevant to health, life, or shared methods',
        'American Academy of Actuaries practice notes and policy statements',
        'NAIC Model Bulletin on the Use of Artificial Intelligence Systems and related state adoptions',
        'State Department of Insurance actuarial bulletins and filing precedents',
        'International Actuarial Association papers and IFRS 17 / Solvency II guidance',
        'Peer-reviewed journals: Variance, North American Actuarial Journal, ASTIN Bulletin',
      ],
      content_formats_preferred: [
        'Peer-reviewed methodology papers',
        'Technical whitepapers with stated assumptions and holdout methodology',
        'Regulatory filings that set useful precedent',
        'Conference presentations from CAS or IAA',
      ],
      content_formats_disliked: [
        'Vendor marketing that makes unqualified accuracy claims',
        'Content that confuses prediction with causation',
        'Anything positioning itself as \'replacing\' actuarial judgment',
        'Case studies without stated assumptions, data period, and holdout approach',
      ],
      average_attention_span_pages: 15,
    },
    disposition_traits: {
      skepticism: 10,
      risk_tolerance: 2,
      technical_fluency: 10,
      jargon_tolerance: 9,
      buzzword_allergy: 10,
      proof_requirement: 10,
    },
    objection_library: {
      stock_objections: [
        'What is the methodology? Specifically — is this a GLM, a GBM, a neural approach, or something else, and why was this choice made?',
        'Show me the holdout. Out-of-sample, out-of-time, and ideally out-of-segment. What was the back-test horizon?',
        'Will this survive a California or New York rate filing? Have you filed it anywhere, and what was the DOI\'s response?',
        'What bias and disparate-impact testing has been done, and against which protected classes? I need to see the results.',
        'What are the stated assumptions? Any model without explicit assumption documentation is unusable.',
        'What is the data lineage? If I can\'t trace a prediction back to the source data and feature derivations, I can\'t sign off.',
        'How does this interact with our existing reserving work?',
        'What is the retraining frequency and what is the drift monitoring approach?',
        'How does this align with ASOP 56 on modeling, and with the NAIC AI Model Bulletin?',
        'What is the explainability approach for an individual prediction?',
        'Who reviewed this methodology? Was it peer-reviewed? By credentialed actuaries, or by data scientists?',
        'What happens to the signed opinion if something in this model\'s output turns out to be wrong and I used it as an input to reserves?',
      ],
      pet_peeves: [
        '\'Black box\' offered as a feature rather than treated as a problem to solve',
        'Accuracy claims presented without holdout, data period, or segment information',
        'Use of \'predictive\' and \'causal\' interchangeably',
        'Vendors who reference \'the algorithm\' as if that were a methodology choice',
        'Content that suggests models can replace rather than inform actuarial judgment',
        'Confidence intervals presented without stated assumptions underlying them',
        'Unqualified accuracy metrics with no out-of-sample test',
      ],
    },
    vocabulary: {
      preferred_terminology: [
        'GLM / GBM / neural (specifying the method)', 'Loss development factor (LDF)',
        'Chain ladder / Bornhuetter-Ferguson / Cape Cod', 'IBNR (incurred but not reported)',
        'Rate adequacy / rate indications', 'Out-of-sample / out-of-time holdout',
        'Pure premium / loss cost', 'Credibility weighting', 'Schedule P',
        'ASOP compliance', 'Disparate impact testing', 'Model governance / model risk management',
        'Stated assumptions', 'Bias-variance tradeoff',
      ],
      forbidden_terms: [
        'Black-box (used as a feature, not a problem)', 'Self-learning model (without governance specification)',
        'Model-free', 'Predictive accuracy (unqualified)', 'Hyper-personalized rating',
        'Next-generation pricing', 'AI-driven reserves', 'AI-powered pricing',
      ],
      domain_shorthand_used: ['LDF', 'IBNR', 'GLM', 'GBM', 'BF / CL', 'ULAE / ALAE', 'ASOP', 'ORSA', 'BCAR', 'IFRS 17', 'NAIC', 'DOI', 'CAS'],
    },
    context_modulators: {
      tier_sensitivity: {
        tier_1: 'A Tier 1 Head Actuary signs opinions on a very large, diversified book. Their focus is on governance of a large actuarial organization, on filings across dozens of jurisdictions, and on defending methodology at a level that withstands rating-agency and regulator scrutiny globally.',
        tier_2: 'A Tier 2 Head Actuary is more technically involved. They may personally lead methodology decisions on key lines and still do hands-on review of pricing and reserving work.',
        tier_3: 'A Tier 3 Head Actuary often wears multiple hats — pricing lead, reserving lead, sometimes capital modeling lead. Budget for actuarial tools is constrained.',
      },
      region_sensitivity: {
        AMER: 'US Head Actuaries are dominated by state-by-state rate filing complexity, NAIC governance (particularly the AI Model Bulletin), and the growing scrutiny on pricing models in California, New York, New Jersey, Colorado, and several others.',
        EMEA: 'European Head Actuaries operate under Solvency II with standard-formula or internal-model capital regimes. IFRS 17 has reshaped financial reporting and actuarial workflows significantly.',
        APAC: 'Varied. Japan and Australia operate with mature actuarial regimes under local standards. China has its own regulatory framework (C-ROSS) with significantly different capital and reserving dynamics.',
      },
    },
  },

  'cio': {
    persona_id: 'cio',
    role_label: 'Chief Information Officer',
    identity: {
      name: 'Marco Iaccarino',
      professional_summary: 'Came from systems integration consulting into insurance carrier IT; deep experience with core system modernization and cloud strategy.',
      role_title: 'Chief Information Officer',
      years_in_role_range: '3-7 years in current role; 20+ years in technology leadership, 10+ years in insurance',
      career_background: 'Mixed backgrounds — some came up through insurance core systems (former Head of Policy Admin, former CTO at a core system vendor like Guidewire or Duck Creek), others came from adjacent financial services or from systems integration firms (Deloitte, Accenture, EY, Capgemini).',
      reporting_line: 'CEO or COO depending on company structure; close partnership with the CFO on technology spend',
    },
    mandate_and_kpis: {
      primary_kpis: [
        'Technology total cost of ownership (TCO) as percent of GWP',
        'Core system availability and performance SLAs',
        'Project and program delivery against commitments (core modernization, cloud migration, data platform)',
        'Cybersecurity posture — incident count, time-to-detect, time-to-contain, audit findings',
        'Integration cost and time-to-integrate for new capabilities',
      ],
      secondary_kpis: [
        'Technical debt reduction (legacy retirement, architecture simplification)',
        'Cloud cost management and efficiency',
        'Data platform utilization and data product adoption',
        'Engineering talent retention and hiring against plan',
        'Vendor count and vendor risk posture',
      ],
      board_pressure_topics: [
        'Core system modernization progress and cost',
        'Cybersecurity and ransomware exposure',
        'AI infrastructure strategy — build vs. buy, cost control, and capability ceiling',
        'Cloud economics — whether the migration is actually delivering promised savings',
        'Data platform strategy and the relationship with the analytics and data science functions',
      ],
      current_year_priorities: [
        'Advancing or stabilizing the core modernization program (Guidewire, Duck Creek, Majesco, Sapiens, EIS, or custom)',
        'Rationalizing the AI and LLM infrastructure strategy — consolidating experimental tooling, establishing governance, managing cost',
        'Reducing integration sprawl by retiring point solutions that overlap',
        'Strengthening cybersecurity posture against ongoing ransomware targeting of insurers',
        'Establishing clear patterns for data residency and sovereignty across operating regions',
      ],
    },
    buying_behavior: {
      budget_authority_usd_range: 'Direct authority typically $2M-$10M; larger investments (core systems, multi-year programs) require CEO and CFO sponsorship and often board approval',
      decision_role: 'economic buyer on infrastructure and enterprise technology; technical buyer on anything touching core systems or data platform',
      typical_deal_stakeholders: [
        'CISO (mandatory on anything with security, data, or cloud implications)',
        'Enterprise Architecture team',
        'Head of Platform or Head of Core Systems',
        'Chief Data Officer or Head of Data Platform',
        'CFO (on TCO and multi-year commitment)',
        'Business sponsors (CUO, CCO, Head of Actuarial, etc.)',
        'Procurement, Legal (especially on data processing and cross-border terms), Vendor Risk Management',
      ],
      procurement_rigor: 'high',
      pilot_appetite: 'medium',
    },
    information_diet: {
      trusted_sources: [
        'Gartner — P&C core systems Magic Quadrant, insurance-specific analyst briefings',
        'Celent P&C practice research',
        'Datos Insights (formerly Novarica) insurance research',
        'Peer CIO networks — ITC Vegas CIO roundtables, InsureTech Connect, CIO Leadership Summits',
        'Cloud hyperscaler insurance reference architectures (AWS for Insurance, Azure for Insurance)',
        'Vendor-neutral integration documentation (Guidewire PartnerConnect, Duck Creek OnDemand)',
        'Specific security publications (SANS, ISC2, insurance ISAC)',
      ],
      content_formats_preferred: [
        'Reference architecture documents with diagrams',
        'Analyst reports with vendor comparisons',
        'Technical case studies that specify deployment model and integration pattern',
        'Peer-written CIO essays on specific technology decisions',
      ],
      content_formats_disliked: [
        'Marketing decks with no architecture',
        'Videos of application UIs',
        'Whitepapers written for business buyers dressed up for IT',
        'Vendor content that buries the deployment model',
      ],
      average_attention_span_pages: 10,
    },
    disposition_traits: {
      skepticism: 8,
      risk_tolerance: 4,
      technical_fluency: 9,
      jargon_tolerance: 7,
      buzzword_allergy: 8,
      proof_requirement: 8,
    },
    objection_library: {
      stock_objections: [
        'What is the deployment model? SaaS, single-tenant SaaS, private cloud, or on-premises? Don\'t tell me \'flexible\' — tell me what you actually ship.',
        'Show me the integration pattern with Guidewire PolicyCenter. Or Duck Creek Policy. Not a generic API diagram.',
        'What\'s your SOC 2 Type II status? ISO 27001? When was the last report, and what were the exceptions?',
        'What\'s the data residency story? I operate in regions where the data cannot leave.',
        'What\'s the total cost of ownership over 5 years, including integration, ongoing support, and the internal resourcing I\'ll have to commit?',
        'Who are you actually running on in production at a carrier of my size, and can I talk to their CIO?',
        'What happens to my data if you get acquired, change your pricing model, or go out of business?',
        'How do you fit alongside our existing data platform investment?',
        'What\'s your position on LLM usage — do you run models on our data, do you call external APIs, and how is that governed?',
        'My team already built something like this on Snowflake or Databricks. Why should I buy yours?',
        'What\'s the API versioning and deprecation policy?',
        'How much of this is actually your product vs. a wrapper around a hyperscaler capability I could use directly?',
      ],
      pet_peeves: [
        '\'API-first\' used without a documented integration catalog',
        '\'Cloud-native\' used to mean \'we run on AWS\'',
        'Security claims without specific certifications or audit reports',
        '\'Seamless integration\' as a standalone claim',
        'Marketing that doesn\'t distinguish between a claims system and a policy admin system',
        'Vendors pitching \'the first AI-powered platform\' in a category where six vendors have been pitching that for four years',
      ],
    },
    vocabulary: {
      preferred_terminology: [
        'Policy admin system (PAS)', 'ClaimCenter / PolicyCenter / BillingCenter',
        'Tenancy model (single-tenant / multi-tenant SaaS)',
        'Integration pattern (event-driven, CDC, API, file-based)',
        'Data residency / data sovereignty', 'SOC 2 Type II', 'TCO / total cost of ownership',
        'Technical debt', 'Reference architecture', 'Service level agreement (SLA)',
        'Disaster recovery / RTO / RPO', 'Zero-trust architecture', 'Data lineage / data catalog',
      ],
      forbidden_terms: [
        'API-first (without a documented integration catalog)', 'Cloud-native (used vaguely)',
        'Seamless integration', 'Single pane of glass', 'End-to-end platform',
        'Future-proof', 'Composable (used as a buzzword)', 'Enterprise-grade (without specifics)',
      ],
      domain_shorthand_used: ['PAS', 'PC / CC / BC (Guidewire)', 'CDC', 'IDP', 'SIEM', 'SOC 2', 'ISO 27001', 'TCO', 'RTO / RPO', 'DR', 'IaC', 'K8s', 'ETL / ELT'],
    },
    context_modulators: {
      tier_sensitivity: {
        tier_1: 'A Tier 1 CIO manages a technology organization that may be thousands of people, with operations across dozens of countries and regulatory regimes. They have the leverage to demand single-tenant deployments, custom contractual terms, and significant roadmap influence.',
        tier_2: 'A Tier 2 CIO is often in the middle of an active core modernization and is more open to strategic technology partnerships. More cost-sensitive than Tier 1. Appreciate vendors who show references from peers of similar scale.',
        tier_3: 'A Tier 3 CIO often runs a small IT organization with heavy reliance on external partners. They want SaaS, fast implementation, and predictable pricing. Severely allergic to anything requiring a data platform or ML ops capability they don\'t have.',
      },
      region_sensitivity: {
        AMER: 'US CIOs deal with state-by-state regulatory variation (including cybersecurity rules like NYDFS Part 500), strong cybersecurity threat landscape (ransomware targeting insurers is persistent).',
        EMEA: 'EMEA CIOs are shaped by GDPR, EIOPA DORA (operational resilience), and local financial-services regulatory regimes. Data residency is a much bigger issue than in the US.',
        APAC: 'APAC CIOs face significant data residency constraints (China, Indonesia, India) and regional cloud availability variation. Regulatory environments range from highly mature (Japan, Australia) to rapidly evolving.',
      },
    },
  },
}
